version: '3.8'

services:
  web:
    image: ildarius116/payment_system-web:latest
    build: .
    container_name: stripe_app
    command: python main/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/main
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: stripe_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: